version: "3"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./pepitas:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4200:4200"
    depends_on:
      - mongodb
